- name: edit eth0 config
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: DEFROUTE=no
- name: edit eth1 config
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.0.1
- name: restart network
  systemd:
    name: network
    state: restarted
- name: install nginx
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
     - epel-release
     - nginx
- name: start nginx
  systemd:
    name: nginx
    state: started
- name: fuck firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
