---
 - name: Update packages
   yum:
     name: '*'
     state: latest
 
 - name: install epel
   yum:
     name: epel-release
     state: present

 - name: install usefull tools
   yum:
     name: "{{ item }}"
     state: latest
   with_items: "{{ tools }}"

 # i know, i do wrong))
 - name: set SeLinux to permissive mode
   selinux:
     policy: targeted
     state: permissive
   #when: "{{ use_selinux }}" == 0

 - name: configure sysctl
   template:
     src: sysctl.j2
     dest: /etc/sysctl.conf
   notify:
     - apply_sysctl

 - name: configure ssh
   template:
     src: sshd_config.j2
     dest: /etc/ssh/sshd_config
   notify:
     - restart_sshd

# - name: disable firewalld
#   systemd:
#     name: firewalld
#     state: stopped
#     masked: yes
#     enabled: no
